<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Kaddouri Bryce" />
    <meta name="description" content="Portefolio BTS SIO de Kaddouri Bryce" />
    <meta name="keywords" content="Portefolio,BTS SIO,2023,SLAM,SISR" />
    <link rel="stylesheet" href="fullpage/examples/examples.css">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:300,400,700" />


    <!-- This following line is optional. Only necessary if you use the option css3:false and you want to use other easing effects rather than "easeInOutCubic". -->



    <link href="dist/output.css" rel="stylesheet">
    <link rel="stylesheet" href="styles/style.css">

    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.1/dist/flowbite.min.css" />
    <script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script>

    </script>


    <style>
        .font-poppins {
            font-family: 'Montserrat', sans-serif;
        }
    </style>


    <title>portefolio - Bryce Kaddouri- SIO 2023 - Profil</title>
    <style>
        video {
            position: fixed;
            top: 50%;
            left: 50%;
            min-width: 100%;
            min-height: 100%;
            width: auto;
            height: auto;
            z-index: -100;
            -webkit-transform: translateX(-50%) translateY(-50%);
            ;
            transform: translateX(-50%) translateY(-50%);
            background: url('images/poster.jpg') no-repeat;
            background-size: cover;
            transition: 1s opacity;
        }

        .slide-bottom {
            -webkit-animation: slide-bottom .5s infinite alternate both;
            animation: slide-bottom .5s infinite alternate both
        }

        .glass {
            /* From https://css.glass */
            background: rgba(255, 255, 255, 0.55);
            border-radius: 16px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            border: 1px solid rgba(255, 255, 255, 0.34);
        }

        #section1 {
            background-image: url(images/logointro.mp4);
            background-size: cover;
        }

        .mr-50 {
            margin-left: 50px;
            top: 0;
        }

        .mt-60 {
            margin-top: 60px;
        }


        /* ----------------------------------------------
 * Generated by Animista on 2022-7-30 0:50:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

        @-webkit-keyframes slide-bottom {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0)
            }

            100% {
                -webkit-transform: translateY(100px);
                transform: translateY(100px)
            }
        }

        @keyframes slide-bottom {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0)
            }

            100% {
                -webkit-transform: translateY(100px);
                transform: translateY(100px)
            }
        }

        @import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&family=Montserrat&family=Nunito:wght@200&family=Playfair+Display:wght@600&display=swap');
    </style>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<header class="sticky top-0 glass">
    <nav style="background-color: #212529" class=" shadow-lg border-gray-200 px-2 sm:px-4 py-0 rounded dark:bg-gray-900 ">
        <div class="container flex flex-wrap justify-between items-center mx-auto">
            <a href="index.html" class="flex items-center">
                <img src="images/logoBK1.png" class="mr-3  mt-1 mb-1 sm:h-9" style="height:60px" alt="BK logo">
                <span class="font-poppins self-center text-white text-2xl font-semibold whitespace-nowrap dark:text-white">Bryce
                    Kaddouri</span>
            </a>
            <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-white rounded-lg md:hidden hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-blue-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                </svg>
            </button>
            <div style="height:50px" class="hidden  w-full mb-auto mt-auto md:block md:w-auto  rounded ml-auto" id="navbar-default">
                <ul class=" flex flex-col   bg-gray-50  ml-5 mr-5  rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                    <li id="accueilLi" class="font-poppins mr-5 ml-5  p-2 text-grey mt-1 mb-1 text-xl" data-menuanchor="accueil"><a href="index.html">Accueil</a>
                    </li>


                    <li class="font-poppins mr-5 ml-5  p-2 text-grey mt-1 mb-1 text-xl" id="prodilLi" data-menuanchor="profil"><a href="profil.html">Profil</a></li>

                    <li class=" font-poppins mr-5 ml-5  p-2 text-grey mt-1 mb-1 text-xl" id="btssioLi" data-menuanchor="btssio"><a href="btssio.html">BTS
                            SIO</a>
                    </li>

                    <li class=" font-poppins mr-5 ml-5  p-2 text-grey mt-1 mb-1 text-xl" id="stageLi" data-menuanchor="stage"><a href="stage.html">Stages</a></li>

                    <li class=" font-poppins mr-5 ml-5  p-2 text-grey mt-1 mb-1 text-xl" id="veilleLi" data-menuanchor="veille"><a href="veille.html">Veilles</a>
                    </li>
                    <li class=" font-poppins pr-5 pl-5 mr-5 ml-5 bg-blue-700 rounded pt-2 pb-2 text-white mt-1 mb-1 text-xl" id="contactLi" data-menuanchor="contact"><a href="contact.html ">Contact</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

</header>

<body class="align-center">

    <div id="infoAction" style="max-width:600px;display:none" class="w-auto mt-5 mb-5 m-auto bg-white shadow-lg rounded-lg p-10 d-none">

    </div>

    <form action="" method="POST" style="max-width:600px;" class="w-auto mt-5 mb-5 m-auto bg-white shadow-lg rounded-lg p-10 ">
        <div class="text-center font-poppins font-semibold text-3xl mb-10">
            <h1 class="">Contactez moi</h1>
        </div>
        <label class="block">
            <span class="block text-sm font-medium text-slate-700">Nom</span>
            <!-- Using form state modifers, the classes can be identical for every input -->
            <input type="text" value="" placeholder="Votre nom" name="nom" id="nom" class="mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
            
          " />
        </label>
        <label class="block">
            <span class="block text-sm font-medium text-slate-700">Prenom</span>
            <!-- Using form state modifers, the classes can be identical for every input -->
            <input type="text" name="prenom" id="prenom" class="mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
            focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
            disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
            invalid:border-pink-500 invalid:text-pink-600
            focus:invalid:border-pink-500 focus:invalid:ring-pink-500
          " />
        </label>
        <label class="block">
            <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                Email
            </span>
            <input name="email" id="email" type="email" name="email" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-sm focus:ring-1" placeholder="you@example.com" />
        </label>
        <label class="block">
            <span class="block text-sm font-medium text-slate-700">Objet du message</span>
            <!-- Using form state modifers, the classes can be identical for every input -->
            <input type="text" name="objet" id="objet" class="mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
            focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
            disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
            invalid:border-pink-500 invalid:text-pink-600
            focus:invalid:border-pink-500 focus:invalid:ring-pink-500
          " />
        </label>
        <label class="block">
            <span class="block text-sm font-medium text-slate-700">Message</span>
            <!-- Using form state modifers, the classes can be identical for every input -->
            <textarea type="textarea" name="message" id="message" class=" h-40 mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
            focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
            disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
            invalid:border-pink-500 invalid:text-pink-600
            focus:invalid:border-pink-500 focus:invalid:ring-pink-500
          "></textarea>
        </label>
        <div class="text-center ">
            <button id="btn-contact" class=" rounded-full  mt-3 bg-blue-700 shadow-lg hover:bg-blue-800 text-white font-poppins pr-3 pl-3 pt-2 pb-2">Save
                Changes</button>
        </div>

        <!-- ... -->
    </form>





    <script>
        $(document).ready(function() {
            const nom = $('#nom').val()
            const prenom = $('#prenom').val()
            const email = $('#email').val()
            const objet = $('#objet').val()
            const message = $('#message').val()
            console.log(nom + " " + prenom + " " + email + " " + objet + " " + message)

            // var $regexname = /^([a-zA-Z]{3,16})$/;
            // $('#nom').on('keyup', function() {
            //     verifInput('#nom')
            // });




            // $('#prenom').on('keyup', function() {

            //     test = verifInput('#prenom')
            //     console.log(test)
            //     values = $('form').serialize()
            //     console.log(values)
            //     // if (!$(this).val().match($regexname)) {
            //     //     // there is a mismatch, hence show the error message
            //     //     // $('#infoAction').empty()
            //     //     // $('#infoAction').append('<p>Message envoyé !</p>')

            //     //     $(this).css('border', '2px groove red')

            //     // } else {
            //     //     // else, do not display message
            //     //     // $('#infoAction').empty()
            //     //     // $('#infoAction').append('<p>Erreur : Veuiller saisir tous les champs !</p>')
            //     //     $(this).css('border', '2px solid green')

            //     // }
            // });



            // $('form').on('keyup', function() {
            //     if (nom != "" && prenom != "" && email != "" && objet != "" && message != "") {
            //         values = $('form').serialize()
            //         $.ajax({
            //             type: "POST",
            //             url: "sendmail.php",
            //             data: values,
            //             dataType: "json",
            //             success: function(response) {
            //                 console.log(response)
            //             }
            //         });
            //         console.log(values)

            //         // $('#infoAction').empty()
            //         // $('#infoAction').append('<p>Message envoyé !</p>')
            //     } else {

            //         // $('#infoAction').empty()
            //         // $('#infoAction').append('<p>Veuillez remplir tous les champs !</p>')
            //     }
            // });$


            $('#prenom').on('keyup', function() {
                var prenomInput = $(this).val()
                var $regexname = /^([a-zA-Z]{3,16})$/;
                if (!$regexname.test(nomInput)) {
                    console.log('test prenom : non valide')
                    $(this).css('border', '2px groove red')
                } else {
                    console.log('test prenom :  valide')
                    $(this).css('border', '2px groove green')
                }
            });
            /* mise en forme input nom (3 caractere minimum ) en fonction du regex */
            $('#nom').on('keyup', function() {
                var nomInput = $(this).val()
                var $regexname = /^([a-zA-Z]{3,16})$/;
                if (!$regexname.test(nomInput)) {
                    console.log('test nom : non valide')
                    $(this).css('border', '2px groove red')
                } else {
                    console.log('test nom :  valide')
                    $(this).css('border', '2px groove green')
                }
            });
            /* mise en forme input email en fonction du regex */
            $('#email').on('keyup', function() {
                var emailinput = $(this).val();
                var patternEmail = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i
                if (!patternEmail.test(emailinput)) {
                    console.log('test non valide')
                    $(this).css('border', '2px groove red')
                } else {
                    console.log('test valide')
                    $(this).css('border', '2px groove green')
                }
            });



            $('#btn-contact').on('click', function(event) {
                event.preventDefault()
                var tableau = $('form').serialize()
                var nom = tableau[0].value
                var prenom = tableau[1].value
                var email = tableau[2].value
                var objet = tableau[3].value
                var message = tableau[4].value








                if (nom != "" && prenom != "" && email != "" && objet != "" && message != "") {


                } else {
                    $('#infoAction').empty()
                    $('#infoAction').append('<p>Veuillez saisir tous les champs ! </p>')
                    console.log('il en manque au moins un ')



                }


            });
        });
    </script>
</body>



</html>